"""Seed catalog of zero-equipment exercises for daily fitness assignments."""

SEED_EXERCISES = [
    # Beginner
    {
        "name": "Squats",
        "description": "Bodyweight squats to wake up your legs.",
        "category": "Strength",
        "difficulty": "Beginner",
        "duration_minutes": 0,
        "target_reps": 20,
        "instructions": "Stand with feet shoulder-width apart. Lower until thighs are parallel, then stand tall. Complete 20 controlled reps.",
        "points": 15,
    },
    {
        "name": "Wall Push-ups",
        "description": "A gentle upper-body push against a wall.",
        "category": "Strength",
        "difficulty": "Beginner",
        "duration_minutes": 0,
        "target_reps": 12,
        "instructions": "Place hands on a wall at shoulder height. Keep your body straight and do 12 slow push-ups.",
        "points": 15,
    },
    {
        "name": "Walking",
        "description": "A brisk campus walk with no equipment.",
        "category": "Walking",
        "difficulty": "Beginner",
        "duration_minutes": 10,
        "target_reps": 0,
        "instructions": "Walk continuously for 10 minutes at a pace where you can still talk.",
        "points": 25,
    },
    {
        "name": "Plank",
        "description": "Hold a strong core position.",
        "category": "Core",
        "difficulty": "Beginner",
        "duration_minutes": 0,
        "target_reps": 30,
        "instructions": "Hold a forearm or high plank for 30 seconds with hips level and core braced.",
        "points": 15,
    },
    {
        "name": "Jumping Jacks",
        "description": "Light cardio to get your heart rate up.",
        "category": "Cardio",
        "difficulty": "Beginner",
        "duration_minutes": 0,
        "target_reps": 30,
        "instructions": "Jump feet out while raising arms overhead, then return. Complete 30 reps.",
        "points": 15,
    },
    {
        "name": "Standing Marches",
        "description": "March in place to loosen hips and raise heart rate.",
        "category": "Mobility",
        "difficulty": "Beginner",
        "duration_minutes": 3,
        "target_reps": 0,
        "instructions": "March in place for 3 minutes, lifting knees comfortably and swinging arms.",
        "points": 10,
    },
    # Intermediate
    {
        "name": "Lunges",
        "description": "Alternating forward lunges for strength and balance.",
        "category": "Strength",
        "difficulty": "Intermediate",
        "duration_minutes": 0,
        "target_reps": 20,
        "instructions": "Step forward into a lunge, then push back to stand. Alternate legs for 20 total reps.",
        "points": 20,
    },
    {
        "name": "Push-ups",
        "description": "Classic floor push-ups.",
        "category": "Strength",
        "difficulty": "Intermediate",
        "duration_minutes": 0,
        "target_reps": 15,
        "instructions": "Keep a straight line from head to heels. Complete 15 push-ups, dropping to knees if needed.",
        "points": 20,
    },
    {
        "name": "Mountain Climbers",
        "description": "Fast core and cardio drive from a plank.",
        "category": "Cardio",
        "difficulty": "Intermediate",
        "duration_minutes": 0,
        "target_reps": 40,
        "instructions": "From a high plank, drive knees toward your chest alternately for 40 total reps.",
        "points": 20,
    },
    {
        "name": "Running",
        "description": "A short continuous run around campus.",
        "category": "Cardio",
        "difficulty": "Intermediate",
        "duration_minutes": 12,
        "target_reps": 0,
        "instructions": "Run continuously for 12 minutes at a steady, conversational pace.",
        "points": 30,
    },
    {
        "name": "Hip Circles",
        "description": "Mobility circles to open the hips.",
        "category": "Mobility",
        "difficulty": "Intermediate",
        "duration_minutes": 0,
        "target_reps": 20,
        "instructions": "Standing on one leg, draw 10 controlled hip circles each side.",
        "points": 15,
    },
    {
        "name": "Hollow Hold",
        "description": "A stronger core isometric.",
        "category": "Core",
        "difficulty": "Intermediate",
        "duration_minutes": 0,
        "target_reps": 40,
        "instructions": "Lie on your back, lift shoulders and legs slightly, and hold for 40 seconds.",
        "points": 20,
    },
    # Advanced
    {
        "name": "Burpees",
        "description": "Full-body power and conditioning.",
        "category": "Cardio",
        "difficulty": "Advanced",
        "duration_minutes": 0,
        "target_reps": 15,
        "instructions": "Drop to the floor, push up, jump feet in, and explode upward. Complete 15 burpees.",
        "points": 35,
    },
    {
        "name": "Advanced Squats",
        "description": "Deeper, slower squat sets with a pause.",
        "category": "Strength",
        "difficulty": "Advanced",
        "duration_minutes": 0,
        "target_reps": 30,
        "instructions": "Perform 30 squats with a 2-second pause at the bottom and full hip extension at the top.",
        "points": 30,
    },
    {
        "name": "Long Cardio Challenge",
        "description": "An extended no-equipment cardio block.",
        "category": "Cardio",
        "difficulty": "Advanced",
        "duration_minutes": 20,
        "target_reps": 0,
        "instructions": "Run, jog, or brisk-walk continuously for 20 minutes without stopping.",
        "points": 40,
    },
    {
        "name": "Pike Push-ups",
        "description": "Shoulder-dominant bodyweight pressing.",
        "category": "Strength",
        "difficulty": "Advanced",
        "duration_minutes": 0,
        "target_reps": 12,
        "instructions": "From a pike position, bend elbows to lower your head, then press up for 12 reps.",
        "points": 30,
    },
    {
        "name": "V-ups",
        "description": "Dynamic core flexion.",
        "category": "Core",
        "difficulty": "Advanced",
        "duration_minutes": 0,
        "target_reps": 20,
        "instructions": "Lie flat, then lift arms and legs to meet above your hips. Complete 20 controlled V-ups.",
        "points": 25,
    },
    {
        "name": "World's Greatest Stretch Flow",
        "description": "A demanding mobility flow for hips and thoracic spine.",
        "category": "Mobility",
        "difficulty": "Advanced",
        "duration_minutes": 8,
        "target_reps": 0,
        "instructions": "Flow through lunges with rotation for 8 minutes, switching sides smoothly.",
        "points": 25,
    },
]
